name: buildperl

on: workflow_dispatch
env:
  PERLVER: "5.40.0"
  URLPERL: https://www.cpan.org/src/5.0/perl-5.40.0.tar.gz
  URL_Encode_EUCJPASCII: https://cpan.metacpan.org/authors/id/N/NE/NEZUMI/Encode-EUCJPASCII-0.03.tar.gz

jobs:
  buildperl:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Perl static
        shell: bash
        run: |
          sudo rm -rf /usr/bin/perl /usr/bin/enc2xs
          mkdir perlsourcestatic && curl -L $URLPERL | tar -xzf - --strip-components=1 --directory=perlsourcestatic
          cd perlsourcestatic && sh +x ./Configure -sde -Dman1dir=none -Dman3dir=none -Dprefix="$PWD/perlprefix" -Aldflags="-lm -ldl" -Accflags="-lm -ldl" -Dusedevel -Uversiononly -Dlibs="-lpthread -ldl -lm -lutil -lc" -Dstatic_ext="mro Devel/Peek File/DosGlob File/Glob Sys/Syslog Sys/Hostname PerlIO/via PerlIO/mmap PerlIO/encoding B attributes Unicode/Normalize Unicode/Collate threads threads/shared IPC/SysV re Digest/MD5 Digest/SHA SDBM_File Math/BigInt/FastCalc Data/Dumper I18N/Langinfo Time/HiRes Time/Piece IO Socket Hash/Util/FieldHash Hash/Util Filter/Util/Call POSIX Encode/Unicode Encode Encode/JP Encode/KR Encode/EBCDIC Encode/CN Encode/Symbol Encode/Byte Encode/TW Compress/Raw/Zlib Compress/Raw/Bzip2 MIME/Base64 Cwd Storable List/Util Fcntl Opcode" && cd -
          make -C perlsourcestatic
          make -C perlsourcestatic install
          export PATH=$PWD/perlsourcestatic/perlprefix/bin:$PATH
          mkdir -p myext
          curl -L $URL_Encode_EUCJPASCII | tar -xzf - --strip-components=1 --directory myext
          cd myext
          perl Makefile.PL LINKTYPE=static
          make && make install

      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: perlsourcestatic/perlprefix/lib/5.4.0/x86_64-linux/auto/Compress/Raw/Zlib/Zlib.a
