name: perlpack

on: workflow_dispatch
# https://github.com/plk/biber/blob/dev/dist/linux_x86_64/build.sh
env:
  URLBIBER: https://github.com/plk/biber/archive/v2.19.tar.gz
  MAKEFLAGS: -j2
  BIBER_DEV_TESTS: 0
  perlv: "5.32.0"
  URLPERL: https://www.cpan.org/src/5.0/perl-5.32.0.tar.gz
  MODULES_def: "-DPERLPACK_mro -DPERLPACK_Devel__Peek -DPERLPACK_File__DosGlob -DPERLPACK_File__Glob -DPERLPACK_Sys__Syslog -DPERLPACK_Sys__Hostname -DPERLPACK_PerlIO__via -DPERLPACK_PerlIO__mmap -DPERLPACK_PerlIO__encoding -DPERLPACK_PerlIO__scalar -DPERLPACK_B -DPERLPACK_attributes -DPERLPACK_Unicode__Normalize -DPERLPACK_Unicode__Collate -DPERLPACK_threads -DPERLPACK_threads__shared -DPERLPACK_IPC__SysV -DPERLPACK_re -DPERLPACK_Digest__MD5 -DPERLPACK_Digest__SHA -DPERLPACK_SDBM_File -DPERLPACK_Math__BigInt__FastCalc -DPERLPACK_Data__Dumper -DPERLPACK_I18N__Langinfo -DPERLPACK_Time__HiRes -DPERLPACK_Time__Piece -DPERLPACK_IO -DPERLPACK_Socket -DPERLPACK_Hash__Util__FieldHash -DPERLPACK_Hash__Util -DPERLPACK_Filter__Util__Call -DPERLPACK_POSIX -DPERLPACK_Encode__Unicode -DPERLPACK_Encode -DPERLPACK_Encode__JP -DPERLPACK_Encode__KR -DPERLPACK_Encode__CN -DPERLPACK_Encode__Symbol -DPERLPACK_Encode__Byte -DPERLPACK_Encode__TW -DPERLPACK_Compress__Raw__Zlib -DPERLPACK_Compress__Raw__Bzip2 -DPERLPACK_MIME__Base64 -DPERLPACK_Cwd -DPERLPACK_Storable -DPERLPACK_List__Util -DPERLPACK_Fcntl -DPERLPACK_Opcode"
  MODULES_a: "mro/mro.a Devel/Peek/Peek.a File/DosGlob/DosGlob.a File/Glob/Glob.a Sys/Syslog/Syslog.a Sys/Hostname/Hostname.a PerlIO/via/via.a PerlIO/mmap/mmap.a PerlIO/encoding/encoding.a PerlIO/scalar/scalar.a B/B.a attributes/attributes.a Unicode/Normalize/Normalize.a Unicode/Collate/Collate.a threads/threads.a threads/shared/shared.a IPC/SysV/SysV.a re/re.a Digest/MD5/MD5.a Digest/SHA/SHA.a SDBM_File/SDBM_File.a Math/BigInt/FastCalc/FastCalc.a Data/Dumper/Dumper.a I18N/Langinfo/Langinfo.a Time/HiRes/HiRes.a Time/Piece/Piece.a IO/IO.a Socket/Socket.a Hash/Util/FieldHash/FieldHash.a Hash/Util/Util.a Filter/Util/Call/Call.a POSIX/POSIX.a Encode/Unicode/Unicode.a Encode/Encode.a Encode/JP/JP.a Encode/KR/KR.a Encode/EBCDIC/EBCDIC.a Encode/CN/CN.a Encode/Symbol/Symbol.a Encode/Byte/Byte.a Encode/TW/TW.a Compress/Raw/Zlib/Zlib.a Compress/Raw/Bzip2/Bzip2.a MIME/Base64/Base64.a Cwd/Cwd.a Storable/Storable.a List/Util/Util.a Fcntl/Fcntl.a Opcode/Opcode.a"
  MODULES_ext: "mro Devel/Peek File/DosGlob File/Glob Sys/Syslog Sys/Hostname PerlIO/via PerlIO/mmap PerlIO/encoding PerlIO/scalar B attributes Unicode/Normalize Unicode/Collate threads threads/shared IPC/SysV re Digest/MD5 Digest/SHA SDBM_File Math/BigInt/FastCalc Data/Dumper I18N/Langinfo Time/HiRes Time/Piece IO Socket Hash/Util/FieldHash Hash/Util Filter/Util/Call POSIX Encode/Unicode Encode Encode/JP Encode/KR Encode/EBCDIC Encode/CN Encode/Symbol Encode/Byte Encode/TW Compress/Raw/Zlib Compress/Raw/Bzip2 MIME/Base64 Cwd Storable List/Util Fcntl Opcode"
  # unneded: SDBM_File Time/Piece Storable
  URL_Params_Validate_XS : https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/Params-Validate-1.31.tar.gz
  URL_Text_BibTeX: https://cpan.metacpan.org/authors/id/A/AM/AMBS/Text-BibTeX-0.89.tar.gz
  URL_IO_Compress_Brotli : https://cpan.metacpan.org/authors/id/T/TI/TIMLEGGE/IO-Compress-Brotli-0.017.tar.gz
  URL_Sort_Key: https://cpan.metacpan.org/authors/id/S/SA/SALVA/Sort-Key-1.33.tar.gz
  URL_Encode_EUCJPASCII: https://cpan.metacpan.org/authors/id/N/NE/NEZUMI/Encode-EUCJPASCII-0.03.tar.gz
  URL_Encode_JIS2K: https://cpan.metacpan.org/authors/id/D/DA/DANKOGAI/Encode-JIS2K-0.05.tar.gz
  URL_Encode_HanExtra: https://cpan.metacpan.org/authors/id/A/AU/AUDREYT/Encode-HanExtra-0.23.tar.gz
  URL_XML_LibXML: https://cpan.metacpan.org/authors/id/S/SH/SHLOMIF/XML-LibXML-2.0210.tar.gz
  URL_autovivification: https://cpan.metacpan.org/authors/id/V/VP/VPIT/autovivification-0.18.tar.gz
  URL_Devel_Caller: https://cpan.metacpan.org/authors/id/R/RC/RCLAMP/Devel-Caller-2.07.tar.gz
  URL_Devel_LexAlias: https://cpan.metacpan.org/authors/id/R/RC/RCLAMP/Devel-LexAlias-0.05.tar.gz
  URL_XML_LibXSLT: https://cpan.metacpan.org/authors/id/S/SH/SHLOMIF/XML-LibXSLT-2.003000.tar.gz
  URL_XML_Parser_Expat: https://cpan.metacpan.org/authors/id/T/TO/TODDR/XML-Parser-2.47.tar.gz
  URL_Unicode_LineBreak: https://cpan.metacpan.org/authors/id/N/NE/NEZUMI/Unicode-LineBreak-2019.001.tar.gz
  URL_Clone: https://cpan.metacpan.org/authors/id/A/AT/ATOOMIC/Clone-0.47.tar.gz
  URL_PadWalker: https://cpan.metacpan.org/authors/id/R/RO/ROBIN/PadWalker-2.5.tar.gz
  URL_PerlIO_utf8_strict: https://cpan.metacpan.org/authors/id/L/LE/LEONT/PerlIO-utf8_strict-0.010.tar.gz
  URL_HTML_Parser: https://cpan.metacpan.org/authors/id/O/OA/OALDERS/HTML-Parser-3.83.tar.gz
  URL_List_MoreUtils_XS: https://cpan.metacpan.org/authors/id/R/RE/REHSACK/List-MoreUtils-XS-0.430.tar.gz
  URL_List_SomeUtils_XS: https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/List-SomeUtils-XS-0.58.tar.gz
  URL_DBI: https://cpan.metacpan.org/authors/id/H/HM/HMBRAND/DBI-1.645.tgz
  URL_Net_SSLeay: https://cpan.metacpan.org/authors/id/C/CH/CHRISN/Net-SSLeay-1.94.tar.gz
  URL_Sub_Identify: https://cpan.metacpan.org/authors/id/R/RG/RGARCIA/Sub-Identify-0.14.tar.gz
  URL_DateTime: https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/DateTime-1.65.tar.gz
  URL_Storable: https://cpan.metacpan.org/authors/id/N/NW/NWCLARK/Storable-3.25.tar.gz
  URL_Variable_Magic: https://cpan.metacpan.org/authors/id/V/VP/VPIT/Variable-Magic-0.64.tar.gz
  URL_Class_XSAccessor: https://cpan.metacpan.org/authors/id/S/SM/SMUELLER/Class-XSAccessor-1.19.tar.gz
  URL_Package_Stash_XS: https://cpan.metacpan.org/authors/id/E/ET/ETHER/Package-Stash-XS-0.30.tar.gz
  URL_Params_Util: https://cpan.metacpan.org/authors/id/R/RE/REHSACK/Params-Util-1.102.tar.gz
  URL_DBD_SQLite: https://cpan.metacpan.org/authors/id/I/IS/ISHIGAKI/DBD-SQLite-1.76.tar.gz
# curl https://fastapi.metacpan.org/v1/download_url/IO::Compress::Brotli | grep download_url | cut -d'"' -f4

jobs:
  perlpack:
    runs-on: ubuntu-20.04
    container: alpine:3.14
    steps:
      - name: Install Prerequisites
        run:  apk add --update --no-cache libnsl libnsl-dev build-base coreutils gdb cmake git xz curl gperf p7zip zip autoconf automake libtool pkgconfig gnupg libxml2-dev libxslt-dev expat-dev openssl-dev openssl # wget perl

      - uses: actions/checkout@v4
      
#      - name: Install Perl dynamic
#        run: |
#          #echo "LD_LIBRARY_PATH=$RUNNER_WORKSPACE/localperldynamic/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
#          # https://github.com/plk/biber/blob/master/dist/linux_x86_64/build.sh
#          #PARLINK="/usr/local/perl/lib/libbtparse.so /usr/lib/x86_64-linux-gnu/libxml2.so.2 /usr/lib/x86_64-linux-gnu/libz.so.1 /usr/lib/x86_64-linux-gnu/libxslt.so.1 /usr/lib/x86_64-linux-gnu/libexslt.so.0 /usr/lib/x86_64-linux-gnu/libssl.so /usr/lib/x86_64-linux-gnu/libcrypto.so"
#          #sudo ln -s /usr/local/perl/lib/5.32.0/x86_64-linux /usr/local/perl/lib/5.32.0/x86_64-linux-thread-multi
#          mkdir perlsourcedynamic
#          wget -nc $URLPERL
#          tar -xf $(basename $URLPERL) --strip-components=1 --directory=perlsourcedynamic
#          cd perlsourcedynamic
#          bash +x ./Configure -sde -Dprefix="$RUNNER_WORKSPACE/localperldynamic"
#          make
#          make install
#          #sudo rm -rf /usr/local/perl && sudo ln -s $RUNNER_WORKSPACE/localperldynamic /usr/local/perl
#          export LD_LIBRARY_PATH="$RUNNER_WORKSPACE/localperldynamic/lib:$LD_LIBRARY_PATH"
#          mkdir biber && wget $URLBIBER && tar -xf $(basename $URLBIBER) --strip-components=1 --directory biber
#          cd biber
#          $RUNNER_WORKSPACE/localperldynamic/bin/cpan -T Module::Build
#          $RUNNER_WORKSPACE/localperldynamic/bin/cpan -T Config::AutoConf ExtUtils::LibBuilder Business::ISBN Business::ISMN Business::ISSN    Class::Accessor Data::Compare Data::Dump Data::Uniqid DateTime::Calendar::Julian DateTime::Format::Builder    Encode::EUCJPASCII Encode::HanExtra Encode::JIS2K Encode::Locale File::Slurper IO::String IPC::Run3 LWP::Protocol::https LWP::UserAgent    Lingua::Translit List::AllUtils List::MoreUtils List::MoreUtils::XS Log::Log4perl Mozilla::CA    Parse::RecDescent PerlIO::utf8_strict Regexp::Common Sort::Key Text::BibTeX Text::CSV Text::CSV_XS Text::Roman URI Unicode::Collate Unicode::GCString Unicode::LineBreak    XML::LibXML XML::LibXML::Simple XML::LibXSLT XML::Writer     autovivification File::Which Test::Differences
#          $RUNNER_WORKSPACE/localperldynamic/bin/cpan -T Test::More IPC::Cmd Unicode::Normalize PerlIO::utf8_strict Storable
#          #./mycpan.sh Pod::Simple::TranscodeSmart Pod::Simple::TranscodeDumb List::SomeUtils::XS List::MoreUtils::PP HTTP::Status HTTP::Date File::Find::Rule IO::Socket::SSL DateTime  Encode::
#          #$RUNNER_WORKSPACE/localperldynamic/bin/perl ./Build installdeps --cpan_client ./mycpan.sh
#          $RUNNER_WORKSPACE/localperldynamic/bin/cpan -T PAR PAR::Packer
#          $RUNNER_WORKSPACE/localperldynamic/bin/perl ./Build.PL
#          $RUNNER_WORKSPACE/localperldynamic/bin/perl ./Build test
#          $RUNNER_WORKSPACE/localperldynamic/bin/perl ./Build install
#          ucpath="/usr/local/perl/lib/${perlv}/Unicode/Collate"
#          if [ -d "/usr/local/perl/lib/site_perl/${perlv}/x86_64-linux-thread-multi/Unicode/Collate" ]; then ucpath="/usr/local/perl/lib/site_perl/${perlv}/x86_64-linux-thread-multi/Unicode/Collate"; fi
#          echo "USING Unicode::Collate at: ${ucpath}, Unicode::Collate has a site_perl version so has been updated since this perl was released"
#          PARMODULE="deprecate Biber::Input::file::bibtex Biber::Input::file::biblatexml Biber::Output::dot Biber::Output::bbl Biber::Output::bblxml Biber::Output::bibtex Biber::Output::biblatexml Pod::Simple::TranscodeSmart Pod::Simple::TranscodeDumb List::MoreUtils::XS List::SomeUtils::XS List::MoreUtils::PP HTTP::Status HTTP::Date Encode:: File::Find::Rule IO::Socket::SSL IO::String PerlIO::utf8_strict Text::CSV_XS DateTime"
#          PARADDFILE="../../data/biber-tool.conf;lib/Biber/biber-tool.conf ../../data/schemata/config.rnc;lib/Biber/config.rnc ../../data/schemata/config.rng;lib/Biber/config.rng ../../data/schemata/bcf.rnc;lib/Biber/bcf.rnc ../../data/schemata/bcf.rng;lib/Biber/bcf.rng ../../lib/Biber/LaTeX/recode_data.xml;lib/Biber/LaTeX/recode_data.xml ../../data/bcf.xsl;lib/Biber/bcf.xsl ${ucpath}/Locale;lib/Unicode/Collate/Locale ${ucpath}/CJK;lib/Unicode/Collate/CJK ${ucpath}/allkeys.txt;lib/Unicode/Collate/allkeys.txt ${ucpath}/keys.txt;lib/Unicode/Collate/keys.txt /usr/local/perl/lib/site_perl/${perlv}/Mozilla/CA/cacert.pem;lib/Mozilla/CA/cacert.pem /usr/local/perl/lib/${perlv}/x86_64-linux-thread-multi/PerlIO;lib/PerlIO /usr/local/perl/lib/${perlv}/x86_64-linux-thread-multi/auto/PerlIO;lib/auto/PerlIO /usr/local/perl/lib/site_perl/${perlv}/Business/ISBN/RangeMessage.xml;lib/Business/ISBN/RangeMessage.xml"
#          PARLINK="$RUNNER_WORKSPACE/localperldynamic/lib/libbtparse.so /usr/lib/libxml2.so /lib/libz.so.1 /usr/lib/libxslt.so.1 /usr/lib/libexslt.so.0 /usr/lib/libssl.so.1.1 /usr/lib/libcrypto.so.1.1"
#          cd ./dist/linux_x86_64
#          PAR_VERBATIM=1 "$RUNNER_WORKSPACE/localperldynamic/bin/pp" -vvv $(printf -- "--module=%s " $PARMODULE) $(printf -- "--link=%s " $PARLINK) $(printf -- "--addfile=%s " $PARADDFILE) --output=biber-linux_x86_64 ../../bin/biber
#          ./biber-linux_x86_64 --help
#          mkdir -p biberunzip && unzip -qq -o ./biber-linux_x86_64 -d biberunzip && find biberunzip # -name '*.so*'
#          #wget $(printf "https://raw.githubusercontent.com/plk/biber/refs/heads/dev/testfiles/%s " Unicode-bib-files.zip Unicode-tests-preserved-NF.zip test.bcf test.bib test.tex testCP.pl)
#          #./biber-linux_x86_64 --validate-control --convert-control test
       
      - name: Install Perl static
        shell: bash
        run: |
          export PERLVER=5.32.0
          export PERLPREFIX=$RUNNER_WORKSPACE/localperlstatic
          export PERLBIN=$RUNNER_WORKSPACE/localperlstatic/bin/perl5.32.0
          export CPANBIN=$RUNNER_WORKSPACE/localperlstatic/bin/cpan5.32.0
          export LD_LIBRARY_PATH=$RUNNER_WORKSPACE/localperlstatic/lib:$LD_LIBRARY_PATH
          #export LD_LIBRARY_PATH=$RUNNER_WORKSPACE/busybiber/packfs/lib:$LD_LIBRARY_PATH
          #export PERLBIN=$RUNNER_WORKSPACE/busybiber/packfs/bin/perl5.32.0
          #export CPANBIN=$RUNNER_WORKSPACE/busybiber/packfs/bin/cpan5.32.0
          #export PERLPREFIX=$RUNNER_WORKSPACE/busybiber/packfs
          mkdir perlsourcestatic && curl -L $URLPERL | tar -xzf - --strip-components=1 --directory=perlsourcestatic
          cd perlsourcestatic && sh +x ./Configure -sde -Dman1dir=none -Dman3dir=none -Dprefix="$RUNNER_WORKSPACE/localperlstatic" -Dinstallprefix="$RUNNER_WORKSPACE/localperlstatic" -Aldflags="-lm -ldl" -Accflags="-lm -ldl" -Dusedevel -Dlibs="-lpthread -ldl -lm -lutil -lc" -Dstatic_ext="$MODULES_ext" -Dextras="DBI" && cd - && make -C perlsourcestatic && make -C perlsourcestatic install
          #cd perlsourcestatic && sh +x ./Configure -sde -Dman1dir=none -Dman3dir=none -Dprefix="/mnt/perlpack" -Dinstallprefix=$RUNNER_WORKSPACE/busybiber/packfs -Aldflags="-lm -ldl" -Accflags="-lm -ldl" -Dusedevel -Dlibs="-lpthread -ldl -lm -lutil -lc" -Dstatic_ext="$MODULES_0ext" -Dextras="DBI" && cd - && make -C perlsourcestatic && make -C perlsourcestatic install
          $PERLBIN $CPANBIN -T Alien::Base::Wrapper Alien::Build Alien::Build::MM Alien::cmake3 Alien::Libxml2 inc::Module::Install Module::Implementation Config::AutoConf ExtUtils::LibBuilder # DBI
          ln -s $PERLPREFIX/bin/enc2xs$PERLVER $PERLPREFIX/bin/enc2xs
          
          for MOD in Sort::Key Encode::EUCJPASCII Encode::JIS2K Encode::HanExtra XML::LibXML autovivification Devel::Caller Devel::LexAlias XML::LibXSLT XML::Parser::Expat Unicode::LineBreak Clone PadWalker  PerlIO::utf8_strict HTML::Parser List::MoreUtils::XS List::SomeUtils::XS DBI Net::SSLeay Sub::Identify DateTime Storable Variable::Magic Class::XSAccessor Package::Stash::XS Params::Util DBD::SQLite    Params::Validate::XS Text::BibTeX IO::Compress::Brotli; do 
              PKG=URL_${MOD//::/_}
              declare -n PKGREF=$PKG; URL=${PKGREF};
              mkdir -p myext/$PKG
              curl -L $URL | tar -xzf - --strip-components=1 --directory myext/$PKG
              cd myext/$PKG
              if [ "$MOD" == "Params::Validate::XS" ] || [ "$MOD" == "Text::BibTeX" ]; then
                  $PERLBIN ./Build.PL
                  $PERLBIN ./Build && $PERLBIN ./Build install
              elif [ "$MOD" == "IO::Compress::Brotli" ]; then
                  $PERLBIN Makefile.PL LINKTYPE=static
                  sed -i 's/$(CP) $(MYEXTLIB) "$@"/$(CP) $(MYEXTLIB) "$(dir $@)"/' Makefile && export MAKEFLAGS=-j1
                  make && make install
              else
                  $PERLBIN Makefile.PL LINKTYPE=static
                  make && make install
              fi
              cd -
          done
          ar crs $PERLPREFIX/lib/site_perl/$PERLVER/x86_64-linux/auto/Params/Validate/XS/XS.a myext/URL_Params_Validate_XS/lib/Params/Validate/XS.o
          ar crs $PERLPREFIX/lib/site_perl/$PERLVER/x86_64-linux/auto/Text/BibTeX/BibTeX.a    myext/URL_Text_BibTeX/xscode/BibTeX.o myext/URL_Text_BibTeX/xscode/btxs_support.o myext/URL_Text_BibTeX/btparse/src/init.o myext/URL_Text_BibTeX/btparse/src/input.o myext/URL_Text_BibTeX/btparse/src/bibtex.o myext/URL_Text_BibTeX/btparse/src/err.o myext/URL_Text_BibTeX/btparse/src/scan.o myext/URL_Text_BibTeX/btparse/src/error.o myext/URL_Text_BibTeX/btparse/src/lex_auxiliary.o myext/URL_Text_BibTeX/btparse/src/parse_auxiliary.o myext/URL_Text_BibTeX/btparse/src/bibtex_ast.o myext/URL_Text_BibTeX/btparse/src/sym.o myext/URL_Text_BibTeX/btparse/src/util.o myext/URL_Text_BibTeX/btparse/src/postprocess.o myext/URL_Text_BibTeX/btparse/src/macros.o myext/URL_Text_BibTeX/btparse/src/traversal.o myext/URL_Text_BibTeX/btparse/src/modify.o myext/URL_Text_BibTeX/btparse/src/names.o myext/URL_Text_BibTeX/btparse/src/tex_tree.o myext/URL_Text_BibTeX/btparse/src/string_util.o
      
#      - name: Build Perl embedded
#        run: |
#          export PERLPREFIX=$RUNNER_WORKSPACE/build
#          export PERLBIN=$PERLPREFIX/bin/perl5.32.0
#          export PERLVER=5.32.0
#          mkdir -p packfs
#          rm -rf packfs/man packfs/lib/*/pod/ || true
#          find packfs -name '*.pod' -o -name '*.ld' -o -name '*.a' -o -name '*.h' -delete || true
#          $PERLBIN perlpack.pl -i packfs -o perlpack.h --prefix=/mnt/perlpack/ --ld=ld
#          
#          #cc -o perlpack perlpack.c -I$PWD/perlsourcestatic -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I$PERLPREFIX/lib/$PERLVER/x86_64-linux/CORE      -Wl,-E -fstack-protector-strong -fwrapv -fno-strict-aliasing -L/usr/local/lib                         $PERLPREFIX/lib/$PERLVER/x86_64-linux/auto/Fcntl/Fcntl.a $PERLPREFIX/lib/$PERLVER/x86_64-linux/auto/IO/IO.a $PERLPREFIX/lib/$PERLVER/x86_64-linux/CORE/libperl.a -lpthread -ldl -lm -lutil -lc -lm 
#      
#          cp $(cc -print-file-name=libc.a) libc_perlpack.a
#          ar x libc_perlpack.a  open.lo close.lo read.lo stat.lo fstat.lo lseek.lo access.lo fopen.lo fileno.lo
#          objcopy --redefine-sym open=orig_open     open.lo
#          objcopy --redefine-sym close=orig_close   close.lo
#          objcopy --redefine-sym read=orig_read     read.lo
#          objcopy --redefine-sym stat=orig_stat     stat.lo
#          objcopy --redefine-sym fstat=orig_fstat   fstat.lo
#          objcopy --redefine-sym lseek=orig_lseek   lseek.lo
#          objcopy --redefine-sym access=orig_access access.lo
#          objcopy --redefine-sym fopen=orig_fopen   fopen.lo
#          objcopy --redefine-sym fileno=orig_fileno fileno.lo
#          ar rs libc_perlpack.a open.lo close.lo read.lo stat.lo fstat.lo lseek.lo access.lo fopen.lo fileno.lo
#          
#          cp perlpack.pl myscript.pl && ld -r -b binary -o myscript.o myscript.pl
#          cc -o perlpack perlpack.c myscript.o -DPACKFS_STATIC -DPACKFS_BUILTIN_PREFIX=/mnt/perlpack/  -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I$PWD/build -I/usr/local/include   -Wl,-E -fstack-protector-strong -fwrapv -fno-strict-aliasing -L/usr/local/lib build/libperl.a libc_perlpack.a -lpthread -ldl -lm -lutil   --static -static -static-libstdc++ -static-libgcc   $MODULES_def $(printf "build/lib/auto/%s " $MODULES_a) @perlpack.h.txt
#          ./perlpack
