name: perlpack

on: workflow_dispatch

env:
  MAKEFLAGS: -j2
  URLPERL: https://www.cpan.org/src/5.0/perl-5.32.0.tar.gz
  URLBIBER: https://github.com/plk/biber/archive/v2.19.tar.gz
  BIBER_DEV_TESTS: 0

jobs:
  perlpack:
    runs-on: ubuntu-20.04
    container: alpine:3.14
    steps:
      - name: Install Prerequisites
        run:  apk add --update --no-cache libnsl libnsl-dev build-base coreutils gdb cmake git xz wget curl perl gperf p7zip zip python3 strace autoconf automake libtool pkgconfig libxml2-dev libxslt-dev && ln -sf python3 /usr/bin/python

      - uses: actions/checkout@v4
      
      - name: Build libc_perlpack.a
        run: make libc_perlpack.a

      - name: Build Perl
        run: make build/libperl.a
      
      - name: Build and test perlpackstatic
        run: |
          make perlpackstatic
          ./perlpackstatic
          ./perlpackstatic -e 'use Cwd;print(Cwd::cwd(),"\n");'
          ./perlpackstatic -e 'open(F,"<","/mnt/perlpack/lib/5.35.4/x86_64-linux/Cwd.pm");print(<F>);'
       
      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: |
            perlpackstatic
            perlpack.h
            libc_perlpack.a
       
       - name: Install Biber
         run: mkdir biber && wget $URLBIBER && tar -xf $(basename $URLBIBER) --strip-components=1 --directory biber
       
       - name: Install Perl dynamic
         run: |
           mkdir perlsourcedynamic
           wget -nc $URLPERL
           tar -xf $(basename $URLPERL) --strip-components=1 --directory=perlsourcedynamic
           cd perlsourcedynamic
           bash +x ./Configure -sde -Dprefix="$RUNNER_WORKSPACE/localperldynamic"
           make
           make install
           sudo rm -rf /usr/local/perl && sudo ln -s $RUNNER_WORKSPACE/localperldynamic /usr/local/perl
           echo "LD_LIBRARY_PATH=$RUNNER_WORKSPACE/localperldynamic/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV

       - name: Install Biber Dependencies Without Test
         run: |
           # libbtparse-dev
           # /home/runner/work/busyperl/localperldynamic/bin
           cd biber
           $RUNNER_WORKSPACE/localperldynamic/bin/cpan -T Module::Build
           $RUNNER_WORKSPACE/localperldynamic/bin/cpan -T Config::AutoConf ExtUtils::LibBuilder Business::ISBN Business::ISMN Business::ISSN    Class::Accessor Data::Compare Data::Dump Data::Uniqid DateTime::Calendar::Julian DateTime::Format::Builder    Encode::EUCJPASCII Encode::HanExtra Encode::JIS2K Encode::Locale File::Slurper IO::String IPC::Run3 LWP::Protocol::https LWP::UserAgent    Lingua::Translit List::AllUtils List::MoreUtils List::MoreUtils::XS Log::Log4perl Mozilla::CA    Parse::RecDescent PerlIO::utf8_strict Regexp::Common Sort::Key Text::BibTeX Text::CSV Text::CSV_XS Text::Roman URI Unicode::Collate Unicode::GCString Unicode::LineBreak    XML::LibXML XML::LibXML::Simple XML::LibXSLT XML::Writer     autovivification File::Which Test::Differences
           $RUNNER_WORKSPACE/localperldynamic/bin/cpan -T Test::More IPC::Cmd Unicode::Normalize PerlIO::utf8_strict Storable
           #./mycpan.sh Pod::Simple::TranscodeSmart Pod::Simple::TranscodeDumb List::SomeUtils::XS List::MoreUtils::PP HTTP::Status HTTP::Date File::Find::Rule IO::Socket::SSL DateTime  Encode::
           $RUNNER_WORKSPACE/localperldynamic/bin/cpan -T PAR PAR::Packer
           $RUNNER_WORKSPACE/localperldynamic/bin/perl ./Build.PL
           #$RUNNER_WORKSPACE/localperldynamic/bin/perl ./Build installdeps --cpan_client ./mycpan.sh
           $RUNNER_WORKSPACE/localperldynamic/bin/perl ./Build test
           $RUNNER_WORKSPACE/localperldynamic/bin/perl ./Build install
           sudo ln -s /usr/local/perl/lib/5.32.0/x86_64-linux /usr/local/perl/lib/5.32.0/x86_64-linux-thread-multi
           cd ./dist/linux_x86_64
           #export PP_OPTS='-vvv'
           # https://github.com/plk/biber/blob/master/dist/linux_x86_64/build.sh
           # Unicode::Collate has a site_perl version so has been updated since this perl was released
           perlv='5.32.0'
           ucpath="/usr/local/perl/lib/${perlv}/Unicode/Collate"
           if [ -d "/usr/local/perl/lib/site_perl/${perlv}/x86_64-linux-thread-multi/Unicode/Collate" ]; then ucpath="/usr/local/perl/lib/site_perl/${perlv}/x86_64-linux-thread-multi/Unicode/Collate"; fi
           echo "USING Unicode::Collate at: ${ucpath}"
           PARMODULE="deprecate Biber::Input::file::bibtex Biber::Input::file::biblatexml Biber::Output::dot Biber::Output::bbl Biber::Output::bblxml Biber::Output::bibtex Biber::Output::biblatexml Pod::Simple::TranscodeSmart Pod::Simple::TranscodeDumb List::MoreUtils::XS List::SomeUtils::XS List::MoreUtils::PP HTTP::Status HTTP::Date Encode:: File::Find::Rule IO::Socket::SSL IO::String PerlIO::utf8_strict Text::CSV_XS DateTime"
           PARLINK="/usr/local/perl/lib/libbtparse.so /usr/lib/x86_64-linux-gnu/libxml2.so.2 /usr/lib/x86_64-linux-gnu/libz.so.1 /usr/lib/x86_64-linux-gnu/libxslt.so.1 /usr/lib/x86_64-linux-gnu/libexslt.so.0 /usr/lib/x86_64-linux-gnu/libssl.so /usr/lib/x86_64-linux-gnu/libcrypto.so"
           PARADDFILE="../../data/biber-tool.conf;lib/Biber/biber-tool.conf ../../data/schemata/config.rnc;lib/Biber/config.rnc ../../data/schemata/config.rng;lib/Biber/config.rng ../../data/schemata/bcf.rnc;lib/Biber/bcf.rnc ../../data/schemata/bcf.rng;lib/Biber/bcf.rng ../../lib/Biber/LaTeX/recode_data.xml;lib/Biber/LaTeX/recode_data.xml ../../data/bcf.xsl;lib/Biber/bcf.xsl ${ucpath}/Locale;lib/Unicode/Collate/Locale ${ucpath}/CJK;lib/Unicode/Collate/CJK ${ucpath}/allkeys.txt;lib/Unicode/Collate/allkeys.txt ${ucpath}/keys.txt;lib/Unicode/Collate/keys.txt /usr/local/perl/lib/site_perl/${perlv}/Mozilla/CA/cacert.pem;lib/Mozilla/CA/cacert.pem /usr/local/perl/lib/${perlv}/x86_64-linux-thread-multi/PerlIO;lib/PerlIO /usr/local/perl/lib/${perlv}/x86_64-linux-thread-multi/auto/PerlIO;lib/auto/PerlIO /usr/local/perl/lib/site_perl/${perlv}/Business/ISBN/RangeMessage.xml;lib/Business/ISBN/RangeMessage.xml"
           PAR_VERBATIM=1 /usr/local/perl/bin/pp $(printf -- "--module=%s " $PARMODULE) $(printf -- "--link=%s " $PARLINK) $(printf -- "--addfile=%s " $PARADDFILE) --output=biber-linux_x86_64 /usr/local/perl/bin/biber
           ./biber-linux_x86_64 --help
           #./biber-linux_x86_64 --validate-control --convert-control test

           mkdir -p biberunzip
           unzip -qq -o biber/dist/linux_x86_64/biber-linux_x86_64 -d biberunzip
           find biberunzip -name '*.so*'
