name: perlpack

on: workflow_dispatch
# https://github.com/plk/biber/blob/dev/dist/linux_x86_64/build.sh
env:
  MAKEFLAGS: -j2
  BIBER_DEV_TESTS: 0
  URLPERL: https://www.cpan.org/src/5.0/perl-5.32.0.tar.gz
  URLBIBER: https://github.com/plk/biber/archive/v2.19.tar.gz
  perlv: "5.32.0"

jobs:
  perlpack:
    runs-on: ubuntu-20.04
    container: alpine:3.14
    steps:
      - name: Install Prerequisites
        run:  apk add --update --no-cache libnsl libnsl-dev build-base coreutils gdb cmake git xz wget curl gperf p7zip zip python3 strace autoconf automake libtool pkgconfig gnupg libxml2-dev libxslt-dev expat-dev openssl-dev openssl

      - uses: actions/checkout@v4
      
#      - name: Build libc_perlpack.a
#        run: make libc_perlpack.a
#
#      - name: Build Perl
#        run: make build/libperl.a
#      
#      - name: Build and test perlpackstatic
#        run: |
#          make perlpackstatic
#          ./perlpackstatic
#          ./perlpackstatic -e 'use Cwd;print(Cwd::cwd(),"\n");'
#          ./perlpackstatic -e 'open(F,"<","/mnt/perlpack/lib/5.35.4/x86_64-linux/Cwd.pm");print(<F>);'
#       
#      - name: Artifacts
#        uses: actions/upload-artifact@v4
#        with:
#          path: |
#            perlpackstatic
#            perlpack.h
#            libc_perlpack.a

#      - name: Install Perl dynamic
#        run: |
#          #echo "LD_LIBRARY_PATH=$RUNNER_WORKSPACE/localperldynamic/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
#          # https://github.com/plk/biber/blob/master/dist/linux_x86_64/build.sh
#          #PARLINK="/usr/local/perl/lib/libbtparse.so /usr/lib/x86_64-linux-gnu/libxml2.so.2 /usr/lib/x86_64-linux-gnu/libz.so.1 /usr/lib/x86_64-linux-gnu/libxslt.so.1 /usr/lib/x86_64-linux-gnu/libexslt.so.0 /usr/lib/x86_64-linux-gnu/libssl.so /usr/lib/x86_64-linux-gnu/libcrypto.so"
#          #sudo ln -s /usr/local/perl/lib/5.32.0/x86_64-linux /usr/local/perl/lib/5.32.0/x86_64-linux-thread-multi
#          mkdir perlsourcedynamic
#          wget -nc $URLPERL
#          tar -xf $(basename $URLPERL) --strip-components=1 --directory=perlsourcedynamic
#          cd perlsourcedynamic
#          bash +x ./Configure -sde -Dprefix="$RUNNER_WORKSPACE/localperldynamic"
#          make
#          make install
#          sudo rm -rf /usr/local/perl && sudo ln -s $RUNNER_WORKSPACE/localperldynamic /usr/local/perl
#          export LD_LIBRARY_PATH="$RUNNER_WORKSPACE/localperldynamic/lib:$LD_LIBRARY_PATH"
#          mkdir biber && wget $URLBIBER && tar -xf $(basename $URLBIBER) --strip-components=1 --directory biber
#          cd biber
#          $RUNNER_WORKSPACE/localperldynamic/bin/cpan -T Module::Build
#          $RUNNER_WORKSPACE/localperldynamic/bin/cpan -T Config::AutoConf ExtUtils::LibBuilder Business::ISBN Business::ISMN Business::ISSN    Class::Accessor Data::Compare Data::Dump Data::Uniqid DateTime::Calendar::Julian DateTime::Format::Builder    Encode::EUCJPASCII Encode::HanExtra Encode::JIS2K Encode::Locale File::Slurper IO::String IPC::Run3 LWP::Protocol::https LWP::UserAgent    Lingua::Translit List::AllUtils List::MoreUtils List::MoreUtils::XS Log::Log4perl Mozilla::CA    Parse::RecDescent PerlIO::utf8_strict Regexp::Common Sort::Key Text::BibTeX Text::CSV Text::CSV_XS Text::Roman URI Unicode::Collate Unicode::GCString Unicode::LineBreak    XML::LibXML XML::LibXML::Simple XML::LibXSLT XML::Writer     autovivification File::Which Test::Differences
#          $RUNNER_WORKSPACE/localperldynamic/bin/cpan -T Test::More IPC::Cmd Unicode::Normalize PerlIO::utf8_strict Storable
#          #./mycpan.sh Pod::Simple::TranscodeSmart Pod::Simple::TranscodeDumb List::SomeUtils::XS List::MoreUtils::PP HTTP::Status HTTP::Date File::Find::Rule IO::Socket::SSL DateTime  Encode::
#          #$RUNNER_WORKSPACE/localperldynamic/bin/perl ./Build installdeps --cpan_client ./mycpan.sh
#          $RUNNER_WORKSPACE/localperldynamic/bin/cpan -T PAR PAR::Packer
#          $RUNNER_WORKSPACE/localperldynamic/bin/perl ./Build.PL
#          $RUNNER_WORKSPACE/localperldynamic/bin/perl ./Build test
#          $RUNNER_WORKSPACE/localperldynamic/bin/perl ./Build install
#          ucpath="/usr/local/perl/lib/${perlv}/Unicode/Collate"
#          if [ -d "/usr/local/perl/lib/site_perl/${perlv}/x86_64-linux-thread-multi/Unicode/Collate" ]; then ucpath="/usr/local/perl/lib/site_perl/${perlv}/x86_64-linux-thread-multi/Unicode/Collate"; fi
#          echo "USING Unicode::Collate at: ${ucpath}, Unicode::Collate has a site_perl version so has been updated since this perl was released"
#          PARMODULE="deprecate Biber::Input::file::bibtex Biber::Input::file::biblatexml Biber::Output::dot Biber::Output::bbl Biber::Output::bblxml Biber::Output::bibtex Biber::Output::biblatexml Pod::Simple::TranscodeSmart Pod::Simple::TranscodeDumb List::MoreUtils::XS List::SomeUtils::XS List::MoreUtils::PP HTTP::Status HTTP::Date Encode:: File::Find::Rule IO::Socket::SSL IO::String PerlIO::utf8_strict Text::CSV_XS DateTime"
#          PARADDFILE="../../data/biber-tool.conf;lib/Biber/biber-tool.conf ../../data/schemata/config.rnc;lib/Biber/config.rnc ../../data/schemata/config.rng;lib/Biber/config.rng ../../data/schemata/bcf.rnc;lib/Biber/bcf.rnc ../../data/schemata/bcf.rng;lib/Biber/bcf.rng ../../lib/Biber/LaTeX/recode_data.xml;lib/Biber/LaTeX/recode_data.xml ../../data/bcf.xsl;lib/Biber/bcf.xsl ${ucpath}/Locale;lib/Unicode/Collate/Locale ${ucpath}/CJK;lib/Unicode/Collate/CJK ${ucpath}/allkeys.txt;lib/Unicode/Collate/allkeys.txt ${ucpath}/keys.txt;lib/Unicode/Collate/keys.txt /usr/local/perl/lib/site_perl/${perlv}/Mozilla/CA/cacert.pem;lib/Mozilla/CA/cacert.pem /usr/local/perl/lib/${perlv}/x86_64-linux-thread-multi/PerlIO;lib/PerlIO /usr/local/perl/lib/${perlv}/x86_64-linux-thread-multi/auto/PerlIO;lib/auto/PerlIO /usr/local/perl/lib/site_perl/${perlv}/Business/ISBN/RangeMessage.xml;lib/Business/ISBN/RangeMessage.xml"
#          PARLINK="$RUNNER_WORKSPACE/localperldynamic/lib/libbtparse.so /usr/lib/libxml2.so /lib/libz.so.1 /usr/lib/libxslt.so.1 /usr/lib/libexslt.so.0 /usr/lib/libssl.so.1.1 /usr/lib/libcrypto.so.1.1"
#          cd ./dist/linux_x86_64
#          PAR_VERBATIM=1 "$RUNNER_WORKSPACE/localperldynamic/bin/pp" -vvv $(printf -- "--module=%s " $PARMODULE) $(printf -- "--link=%s " $PARLINK) $(printf -- "--addfile=%s " $PARADDFILE) --output=biber-linux_x86_64 ../../bin/biber
#          ./biber-linux_x86_64 --help
#          mkdir -p biberunzip && unzip -qq -o ./biber-linux_x86_64 -d biberunzip && find biberunzip # -name '*.so*'
#          #wget $(printf "https://master.dl.sourceforge.net/project/biblatex-biber/biblatex-biber/testfiles/%s " test.bib test.bcf test-dev.bcf unifont.ttf)
#          #./biber-linux_x86_64 --validate-control --convert-control test
       
      - name: Install Perl static
        run: |
          mkdir perlsourcestatic
          wget -nc $URLPERL
          tar -xf $(basename $URLPERL) --strip-components=1 --directory=perlsourcestatic
          cd perlsourcestatic
          bash +x ./Configure -sde -Dprefix="$RUNNER_WORKSPACE/localperlstatic" -Dextras="DBI" -Dstatic_ext="attributes B Cwd Data/Dumper Devel/Peek Digest/MD5 Digest/SHA Encode Encode/Unicode Encode/CN Encode/KR Encode/TW Encode/JP  Encode/Symbol Encode/EBCDIC Encode/Byte Fcntl File/Glob Hash/Util I18N/Langinfo IO List/Util mro Opcode PerlIO/encoding PerlIO/scalar PerlIO/via POSIX PerlIO/mmap Time/HiRes re Socket  Unicode/Normalize Unicode/Collate Compress/Raw/Zlib Compress/Raw/Bzip2 threads threads/shared Sys/Syslog Sys/Hostname File/DosGlob Math/BigInt/FastCalc Hash/Util/FieldHash Filter/Util/Call IPC/SysV MIME/Base64" -Dusedevel -Accflags="-lm -ldl" -Aldflags="-lm -ldl" -Dlibs="-lpthread -ldl -lm -lutil -lc"
          make
          make install
          $RUNNER_WORKSPACE/localperlstatic/bin/perl5.32.0 -e "print('hello world');"
          ln -s $RUNNER_WORKSPACE/localperlstatic/bin/enc2xs5.32.0 $RUNNER_WORKSPACE/localperlstatic/bin/enc2xs
          find $RUNNER_WORKSPACE/localperlstatic
          #$RUNNER_WORKSPACE/localperlstatic/bin/cpan5.32.0 -T Alien::Base::Wrapper Alien::cmake3 inc::Module::Install
          echo "$RUNNER_WORKSPACE/localperlstatic/bin" >> $GITHUB_PATH
          echo "LD_LIBRARY_PATH=$RUNNER_WORKSPACE/localperlstatic/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
      
      - name: Install build-time deps
        run: $RUNNER_WORKSPACE/localperlstatic/bin/cpan5.32.0 -T Alien::Base::Wrapper Alien::Build Alien::Build::MM Alien::cmake3 Alien::Libxml2 inc::Module::Install Module::Implementation Config::AutoConf ExtUtils::LibBuilder # DBI
      
      - name: Install Perl static extra packages
        run: |
          export PERLBIN=$RUNNER_WORKSPACE/localperlstatic/bin/perl5.32.0
          for MOD in Sort::Key Encode::EUCJPASCII Encode::JIS2K Encode::HanExtra XML::LibXML autovivification Devel::Caller Devel::LexAlias XML::LibXSLT XML::Parser::Expat Unicode::LineBreak Clone PadWalker  PerlIO::utf8_strict HTML::Parser List::MoreUtils::XS List::SomeUtils::XS DBI Net::SSLeay Sub::Identify DateTime Storable Variable::Magic Class::XSAccessor Package::Stash::XS Params::Util DBD::SQLite; do 
              URL=$(wget -q -O - https://fastapi.metacpan.org/v1/download_url/$MOD | grep download_url | cut -d'"' -f4)
              PKG=${MOD//::/-}
              mkdir -p myextsource myext/$PKG
              wget -nc $URL -P myextsource
              tar -xf myextsource/$(basename $URL) --strip-components=1 --directory myext/$PKG
              cd myext/$PKG
              $PERLBIN Makefile.PL LINKTYPE=static
              make
              make install
              cd ../..
           done

      - name: Install Brotli
        run: |
          export PERLBIN=$RUNNER_WORKSPACE/localperlstatic/bin/perl5.32.0
          URL=$(wget -q -O - https://fastapi.metacpan.org/v1/download_url/IO::Compress::Brotli | grep download_url | cut -d'"' -f4)
          mkdir -p myextsource myext/IO-Compress-Brotli
          wget -nc $URL -P myextsource
          tar -xf myextsource/$(basename $URL) --strip-components=1 --directory myext/IO-Compress-Brotli
          cd myext/IO-Compress-Brotli
          $PERLBIN Makefile.PL LINKTYPE=static
          sed -i 's/$(CP) $(MYEXTLIB) "$@"/$(CP) $(MYEXTLIB) "$(dir $@)"/' Makefile
          make
          make install
      
      - name: Install Params/Validate/XS
        run: |
          export PERLBIN=$RUNNER_WORKSPACE/localperlstatic/bin/perl5.32.0
          URL=$(wget -q -O - https://fastapi.metacpan.org/v1/download_url/Params::Validate::XS | grep download_url | cut -d'"' -f4)
          mkdir -p myextsource myext/Params-Validate-XS
          wget -nc $URL -P myextsource
          tar -xf myextsource/$(basename $URL) --strip-components=1 --directory myext/Params-Validate-XS
          cd myext/Params-Validate-XS
          $PERLBIN ./Build.PL
          $PERLBIN ./Build
          $PERLBIN ./Build install
          ar crs ../../../localperlstatic/lib/site_perl/5.32.0/x86_64-linux/auto/Params/Validate/XS/XS.a lib/Params/Validate/XS.o
      
#      - name: Install Text/BibTeX
#        run: |
#          export PERLBIN=$RUNNER_WORKSPACE/localperlstatic/bin/perl5.32.0
#          URL=$(wget -q -O - https://fastapi.metacpan.org/v1/download_url/Text::BibTeX | grep download_url | cut -d'"' -f4)
#          mkdir -p myextsource myext/Text-BibTeX
#          wget -nc $URL -P myextsource
#          tar -xf myextsource/$(basename $URL) --strip-components=1 --directory myext/Text-BibTeX
#          cd myext/Text-BibTeX
#          $PERLBIN ./Build.PL
#          $PERLBIN ./Build
#          $PERLBIN ./Build install
#          ar crs  ../../../localperlstatic/lib/site_perl/5.32.0/x86_64-linux/auto/Text/BibTeX/BibTeX.a    xscode/BibTeX.o xscode/btxs_support.o btparse/src/init.o btparse/src/input.o btparse/src/bibtex.o btparse/src/err.o btparse/src/scan.o btparse/src/error.o btparse/src/lex_auxiliary.o btparse/src/parse_auxiliary.o btparse/src/bibtex_ast.o btparse/src/sym.o btparse/src/util.o btparse/src/postprocess.o btparse/src/macros.o btparse/src/traversal.o btparse/src/modify.o btparse/src/names.o btparse/src/tex_tree.o btparse/src/string_util.o
#
#      - name: Build Perl embedded
#        run: |
#          gcc -o staticperl_biber staticperl_biber.c -I$PWD/perlsourcestatic -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I$RUNNER_WORKSPACE/localperlstatic/lib/5.32.0/x86_64-linux/CORE      -Wl,-E -fstack-protector-strong -fwrapv -fno-strict-aliasing -L/usr/local/lib                         $RUNNER_WORKSPACE/localperlstatic/lib/5.32.0/x86_64-linux/auto/Fcntl/Fcntl.a $RUNNER_WORKSPACE/localperlstatic/lib/5.32.0/x86_64-linux/auto/IO/IO.a $RUNNER_WORKSPACE/localperlstatic/lib/5.32.0/x86_64-linux/CORE/libperl.a -lpthread -ldl -lm -lutil -lc -lm 
#          ldd staticperl_biber
#          ./staticperl_biber
